// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for DeployStatus.
const (
	DeployStatusCONFIGURING DeployStatus = "CONFIGURING"
	DeployStatusDELETED     DeployStatus = "DELETED"
	DeployStatusDELETING    DeployStatus = "DELETING"
	DeployStatusOPTIMIZING  DeployStatus = "OPTIMIZING"
	DeployStatusPAUSED      DeployStatus = "PAUSED"
	DeployStatusPAUSING     DeployStatus = "PAUSING"
	DeployStatusQUEUED      DeployStatus = "QUEUED"
	DeployStatusREADY       DeployStatus = "READY"
	DeployStatusRESUMING    DeployStatus = "RESUMING"
	DeployStatusUNSTABLE    DeployStatus = "UNSTABLE"
	DeployStatusUPGRADING   DeployStatus = "UPGRADING"
)

// Defines values for EnvironmentTag.
const (
	EnvironmentTagDEV  EnvironmentTag = "DEV"
	EnvironmentTagPROD EnvironmentTag = "PROD"
)

// Defines values for FileImportDefinitionType.
const (
	CSV     FileImportDefinitionType = "CSV"
	PARQUET FileImportDefinitionType = "PARQUET"
)

// Defines values for FileImportSourceType.
const (
	FileImportSourceTypeHTTP     FileImportSourceType = "HTTP"
	FileImportSourceTypeINTERNAL FileImportSourceType = "INTERNAL"
	FileImportSourceTypeS3       FileImportSourceType = "S3"
)

// Defines values for FileImportState.
const (
	FileImportStateCANCELLED        FileImportState = "CANCELLED"
	FileImportStateFAILURE          FileImportState = "FAILURE"
	FileImportStateINQUEUE          FileImportState = "IN_QUEUE"
	FileImportStatePAUSED           FileImportState = "PAUSED"
	FileImportStateRETRYING         FileImportState = "RETRYING"
	FileImportStateRUNNING          FileImportState = "RUNNING"
	FileImportStateSKIPPED          FileImportState = "SKIPPED"
	FileImportStateSUCCESS          FileImportState = "SUCCESS"
	FileImportStateWAITINGFORUPLOAD FileImportState = "WAITING_FOR_UPLOAD"
)

// Defines values for ForkStrategy.
const (
	LASTSNAPSHOT ForkStrategy = "LAST_SNAPSHOT"
	NOW          ForkStrategy = "NOW"
	PITR         ForkStrategy = "PITR"
)

// Defines values for ReadReplicaSetStatus.
const (
	ReadReplicaSetStatusActive   ReadReplicaSetStatus = "active"
	ReadReplicaSetStatusCreating ReadReplicaSetStatus = "creating"
	ReadReplicaSetStatusDeleting ReadReplicaSetStatus = "deleting"
	ReadReplicaSetStatusError    ReadReplicaSetStatus = "error"
	ReadReplicaSetStatusResizing ReadReplicaSetStatus = "resizing"
)

// Defines values for ServiceCreateAddons.
const (
	Ai         ServiceCreateAddons = "ai"
	TimeSeries ServiceCreateAddons = "time-series"
)

// Defines values for ServiceType.
const (
	POSTGRES    ServiceType = "POSTGRES"
	TIMESCALEDB ServiceType = "TIMESCALEDB"
	VECTOR      ServiceType = "VECTOR"
)

// Defines values for SetEnvironmentInputEnvironment.
const (
	SetEnvironmentInputEnvironmentDEV  SetEnvironmentInputEnvironment = "DEV"
	SetEnvironmentInputEnvironmentPROD SetEnvironmentInputEnvironment = "PROD"
)

// Defines values for UpdateFileImportRequestType.
const (
	Cancel UpdateFileImportRequestType = "cancel"
	Labels UpdateFileImportRequestType = "labels"
	Retry  UpdateFileImportRequestType = "retry"
)

// Defines values for GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceType.
const (
	GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceTypeHTTP     GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceType = "HTTP"
	GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceTypeINTERNAL GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceType = "INTERNAL"
	GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceTypeS3       GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceType = "S3"
)

// ColumnMapping defines model for ColumnMapping.
type ColumnMapping struct {
	// Destination Destination column name in the target table.
	Destination string `json:"destination"`

	// Source Source column name in the original file.
	Source string `json:"source"`
}

// ConnectionPooler defines model for ConnectionPooler.
type ConnectionPooler struct {
	Endpoint *Endpoint `json:"endpoint,omitempty"`
}

// CreateFileImportInput defines model for CreateFileImportInput.
type CreateFileImportInput struct {
	// Definition File format definition. Only csv or parquet should be set based on type.
	Definition FileImportDefinition `json:"definition"`

	// Id Unique identifier for this file import.
	Id string `json:"id"`

	// Labels Optional labels for filtering.
	Labels   *[]FileImportLabel `json:"labels,omitempty"`
	Settings *ImportSettings    `json:"settings,omitempty"`

	// Source Source configuration for the file import. Only one of s3, http, or internal should be set based on type.
	Source          FileImportSource `json:"source"`
	TableIdentifier TableIdentifier  `json:"table_identifier"`
}

// DeployStatus defines model for DeployStatus.
type DeployStatus string

// Endpoint defines model for Endpoint.
type Endpoint struct {
	Host *string `json:"host,omitempty"`
	Port *int    `json:"port,omitempty"`
}

// EnvironmentTag The environment tag for the service.
type EnvironmentTag string

// Error defines model for Error.
type Error struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// FileImport defines model for FileImport.
type FileImport struct {
	// CreatedAt Creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Definition File format definition. Only csv or parquet should be set based on type.
	Definition FileImportDefinition `json:"definition"`

	// Id Unique file import identifier.
	Id string `json:"id"`

	// Labels Labels for filtering and organization.
	Labels []FileImportLabel `json:"labels"`

	// ProjectId Project identifier.
	ProjectId string `json:"project_id"`

	// ServiceId Service identifier.
	ServiceId string          `json:"service_id"`
	Settings  *ImportSettings `json:"settings,omitempty"`

	// Size File size in bytes.
	Size int `json:"size"`

	// Source Source configuration for the file import. Only one of s3, http, or internal should be set based on type.
	Source          FileImportSource    `json:"source"`
	State           FileImportStateInfo `json:"state"`
	TableIdentifier TableIdentifier     `json:"table_identifier"`

	// UpdatedAt Last update timestamp.
	UpdatedAt time.Time `json:"updated_at"`
}

// FileImportDefinition File format definition. Only csv or parquet should be set based on type.
type FileImportDefinition struct {
	Csv     *FileImportDefinitionCSV     `json:"csv,omitempty"`
	Parquet *FileImportDefinitionParquet `json:"parquet,omitempty"`

	// Type The file format type.
	Type FileImportDefinitionType `json:"type"`
}

// FileImportDefinitionCSV defines model for FileImportDefinitionCSV.
type FileImportDefinitionCSV struct {
	// AutoColumnMapping Automatically map columns by matching header names. Requires skip_header=true. Mutually exclusive with column_names and column_mappings.
	AutoColumnMapping *bool `json:"auto_column_mapping,omitempty"`

	// ColumnMappings Mappings from source to destination columns. Requires skip_header=true. Mutually exclusive with column_names and auto_column_mapping.
	ColumnMappings *[]ColumnMapping `json:"column_mappings,omitempty"`

	// ColumnNames Column names matching the destination table. Mutually exclusive with column_mappings and auto_column_mapping.
	ColumnNames *[]string `json:"column_names,omitempty"`

	// Delimiter The delimiter character for CSV files.
	Delimiter *string `json:"delimiter,omitempty"`

	// SkipHeader Whether to skip the first row as a header. Required for column_mappings and auto_column_mapping.
	SkipHeader *bool `json:"skip_header,omitempty"`
}

// FileImportDefinitionParquet defines model for FileImportDefinitionParquet.
type FileImportDefinitionParquet struct {
	// AutoColumnMapping Automatically map columns by matching header names. Mutually exclusive with column_mappings.
	AutoColumnMapping *bool `json:"auto_column_mapping,omitempty"`

	// ColumnMappings Mappings from source to destination columns. Mutually exclusive with auto_column_mapping.
	ColumnMappings *[]ColumnMapping `json:"column_mappings,omitempty"`
}

// FileImportDefinitionType The file format type.
type FileImportDefinitionType string

// FileImportHTTPSource defines model for FileImportHTTPSource.
type FileImportHTTPSource struct {
	// Url The HTTP(S) URL to download the file from.
	Url string `json:"url"`
}

// FileImportInternalSource defines model for FileImportInternalSource.
type FileImportInternalSource struct {
	// Id Internal identifier for the uploaded file.
	Id string `json:"id"`
}

// FileImportLabel defines model for FileImportLabel.
type FileImportLabel struct {
	// Key Label key for filtering.
	Key string `json:"key"`

	// Value Label value.
	Value string `json:"value"`
}

// FileImportS3Source defines model for FileImportS3Source.
type FileImportS3Source struct {
	// Bucket The S3 bucket name.
	Bucket string `json:"bucket"`

	// Id The identifier for this source (deprecated, not actively used).
	Id *string `json:"id,omitempty"`

	// Key The S3 object key.
	Key string `json:"key"`

	// RoleArn AWS IAM role ARN for accessing the S3 bucket.
	RoleArn *string `json:"role_arn,omitempty"`
}

// FileImportSource Source configuration for the file import. Only one of s3, http, or internal should be set based on type.
type FileImportSource struct {
	Http     *FileImportHTTPSource     `json:"http,omitempty"`
	Internal *FileImportInternalSource `json:"internal,omitempty"`
	S3       *FileImportS3Source       `json:"s3,omitempty"`

	// Type The type of source for the file import.
	Type FileImportSourceType `json:"type"`
}

// FileImportSourceType The type of source for the file import.
type FileImportSourceType string

// FileImportState Current state of the file import operation.
type FileImportState string

// FileImportStateInfo defines model for FileImportStateInfo.
type FileImportStateInfo struct {
	// FailureReason Detailed failure reason if state is FAILURE.
	FailureReason *string `json:"failure_reason,omitempty"`
	Progress      *struct {
		// Current Current progress value.
		Current *int `json:"current,omitempty"`

		// Message Human-readable progress message.
		Message *string `json:"message,omitempty"`

		// Total Total expected value.
		Total *int `json:"total,omitempty"`
	} `json:"progress,omitempty"`

	// State Current state of the file import operation.
	State FileImportState `json:"state"`

	// Timelines History of state transitions.
	Timelines *[]FileImportStateTimeline `json:"timelines,omitempty"`
}

// FileImportStateTimeline defines model for FileImportStateTimeline.
type FileImportStateTimeline struct {
	// At Timestamp when this state was entered.
	At *time.Time `json:"at,omitempty"`

	// Payload Additional information about the state change.
	Payload *struct {
		// FailureReason Reason for failure, if applicable.
		FailureReason *string `json:"failure_reason,omitempty"`

		// RetryAt Scheduled retry time, if applicable.
		RetryAt *time.Time `json:"retry_at,omitempty"`
	} `json:"payload,omitempty"`

	// State The state that was entered.
	State *string `json:"state,omitempty"`
}

// ForkServiceCreate Create a fork of an existing service. Service type, region code, and storage are always inherited from the parent service.
// HA replica count is always set to 0 for forked services.
type ForkServiceCreate struct {
	// CpuMillis The initial CPU allocation in milli-cores, or 'shared' for a shared-resource service. If not provided, will inherit from parent service.
	CpuMillis *string `json:"cpu_millis,omitempty"`

	// EnvironmentTag The environment tag for the service.
	EnvironmentTag *EnvironmentTag `json:"environment_tag,omitempty"`

	// ForkStrategy Strategy for creating the fork:
	// - LAST_SNAPSHOT: Use existing snapshot for fast fork
	// - NOW: Create new snapshot for up-to-date fork
	// - PITR: Point-in-time recovery using target_time
	ForkStrategy ForkStrategy `json:"fork_strategy"`

	// MemoryGbs The initial memory allocation in gigabytes, or 'shared' for a shared-resource service. If not provided, will inherit from parent service.
	MemoryGbs *string `json:"memory_gbs,omitempty"`

	// Name A human-readable name for the forked service. If not provided, will use parent service name with "-fork" suffix.
	Name *string `json:"name,omitempty"`

	// TargetTime Target time for point-in-time recovery. Required when fork_strategy is PITR.
	TargetTime *time.Time `json:"target_time,omitempty"`
}

// ForkSpec defines model for ForkSpec.
type ForkSpec struct {
	IsStandby *bool   `json:"is_standby,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
	ServiceId *string `json:"service_id,omitempty"`
}

// ForkStrategy Strategy for creating the fork:
// - LAST_SNAPSHOT: Use existing snapshot for fast fork
// - NOW: Create new snapshot for up-to-date fork
// - PITR: Point-in-time recovery using target_time
type ForkStrategy string

// GeneratePresignedURLInput defines model for GeneratePresignedURLInput.
type GeneratePresignedURLInput struct {
	// ContentLength Exact size of the file to upload in bytes. Must match the Content-Length header during upload.
	ContentLength int `json:"content_length"`

	// Id Unique identifier for the file. This will be used later when creating the file import.
	Id string `json:"id"`
}

// GeneratePresignedURLResponse defines model for GeneratePresignedURLResponse.
type GeneratePresignedURLResponse struct {
	// Url Presigned S3 URL for uploading the file. Valid for a limited time.
	Url string `json:"url"`
}

// HAReplica defines model for HAReplica.
type HAReplica struct {
	// ReplicaCount Number of high-availability replicas (all replicas are asynchronous by default).
	ReplicaCount *int `json:"replica_count,omitempty"`

	// SyncReplicaCount Number of synchronous high-availability replicas.
	SyncReplicaCount *int `json:"sync_replica_count,omitempty"`
}

// ImportSettings defines model for ImportSettings.
type ImportSettings struct {
	// OnConflictDoNothing Handle conflicts by ignoring conflicting rows.
	OnConflictDoNothing *bool `json:"on_conflict_do_nothing,omitempty"`
}

// ListFileImportResponse defines model for ListFileImportResponse.
type ListFileImportResponse struct {
	// FileImports List of file imports.
	FileImports []FileImport `json:"file_imports"`
	PageInfo    PageInfo     `json:"page_info"`
}

// PageInfo defines model for PageInfo.
type PageInfo struct {
	// EndCursor Cursor for fetching the next page.
	EndCursor *string `json:"end_cursor,omitempty"`

	// HasNextPage Whether there is a next page.
	HasNextPage bool `json:"has_next_page"`

	// HasPreviousPage Whether there is a previous page.
	HasPreviousPage bool `json:"has_previous_page"`

	// StartCursor Cursor for fetching the previous page.
	StartCursor *string `json:"start_cursor,omitempty"`
}

// Peering defines model for Peering.
type Peering struct {
	ErrorMessage   *string `json:"error_message,omitempty"`
	Id             *string `json:"id,omitempty"`
	PeerAccountId  *string `json:"peer_account_id,omitempty"`
	PeerRegionCode *string `json:"peer_region_code,omitempty"`
	PeerVpcId      *string `json:"peer_vpc_id,omitempty"`
	ProvisionedId  *string `json:"provisioned_id,omitempty"`
	Status         *string `json:"status,omitempty"`
}

// PeeringCreate defines model for PeeringCreate.
type PeeringCreate struct {
	PeerAccountId  string `json:"peer_account_id"`
	PeerRegionCode string `json:"peer_region_code"`
	PeerVpcId      string `json:"peer_vpc_id"`
}

// ReadReplicaSet defines model for ReadReplicaSet.
type ReadReplicaSet struct {
	ConnectionPooler *ConnectionPooler `json:"connection_pooler,omitempty"`

	// CpuMillis CPU allocation in milli-cores.
	CpuMillis *int      `json:"cpu_millis,omitempty"`
	Endpoint  *Endpoint `json:"endpoint,omitempty"`
	Id        *string   `json:"id,omitempty"`

	// MemoryGbs Memory allocation in gigabytes.
	MemoryGbs *int `json:"memory_gbs,omitempty"`

	// Metadata Additional metadata for the read replica set
	Metadata *struct {
		// Environment Environment tag for the read replica set
		Environment *string `json:"environment,omitempty"`
	} `json:"metadata,omitempty"`
	Name *string `json:"name,omitempty"`

	// Nodes Number of nodes in the replica set.
	Nodes  *int                  `json:"nodes,omitempty"`
	Status *ReadReplicaSetStatus `json:"status,omitempty"`
}

// ReadReplicaSetStatus defines model for ReadReplicaSet.Status.
type ReadReplicaSetStatus string

// ReadReplicaSetCreate defines model for ReadReplicaSetCreate.
type ReadReplicaSetCreate struct {
	// CpuMillis The initial CPU allocation in milli-cores.
	CpuMillis int `json:"cpu_millis"`

	// MemoryGbs The initial memory allocation in gigabytes.
	MemoryGbs int `json:"memory_gbs"`

	// Name A human-readable name for the read replica.
	Name string `json:"name"`

	// Nodes Number of nodes to create in the replica set.
	Nodes int `json:"nodes"`
}

// ResizeInput defines model for ResizeInput.
type ResizeInput struct {
	// CpuMillis The new CPU allocation in milli-cores (e.g., 1000 for 1 vCPU).
	CpuMillis int `json:"cpu_millis"`

	// MemoryGbs The new memory allocation in gigabytes.
	MemoryGbs int `json:"memory_gbs"`

	// Nodes The new number of nodes in the replica set.
	Nodes *int `json:"nodes,omitempty"`
}

// Service defines model for Service.
type Service struct {
	ConnectionPooler *ConnectionPooler `json:"connection_pooler,omitempty"`

	// Created Creation timestamp
	Created    *time.Time `json:"created,omitempty"`
	Endpoint   *Endpoint  `json:"endpoint,omitempty"`
	ForkedFrom *ForkSpec  `json:"forked_from,omitempty"`
	HaReplicas *HAReplica `json:"ha_replicas,omitempty"`

	// InitialPassword The initial password for the service.
	InitialPassword *string `json:"initial_password,omitempty"`

	// Metadata Additional metadata for the service
	Metadata *struct {
		// Environment Environment tag for the service
		Environment *string `json:"environment,omitempty"`
	} `json:"metadata,omitempty"`

	// Name The name of the service.
	Name *string `json:"name,omitempty"`

	// Paused Whether the service is paused
	Paused *bool `json:"paused,omitempty"`

	// ProjectId The project this service belongs to.
	ProjectId       *string           `json:"project_id,omitempty"`
	ReadReplicaSets *[]ReadReplicaSet `json:"read_replica_sets,omitempty"`

	// RegionCode The cloud region where the service is hosted.
	RegionCode *string `json:"region_code,omitempty"`

	// Resources List of resources allocated to the service
	Resources *[]struct {
		// Id Resource identifier
		Id *string `json:"id,omitempty"`

		// Spec Resource specification
		Spec *struct {
			// CpuMillis CPU allocation in millicores
			CpuMillis *int `json:"cpu_millis,omitempty"`

			// MemoryGbs Memory allocation in gigabytes
			MemoryGbs *int `json:"memory_gbs,omitempty"`

			// VolumeType Type of storage volume
			VolumeType *string `json:"volume_type,omitempty"`
		} `json:"spec,omitempty"`
	} `json:"resources,omitempty"`

	// ServiceId The unique identifier for the service.
	ServiceId   *string       `json:"service_id,omitempty"`
	ServiceType *ServiceType  `json:"service_type,omitempty"`
	Status      *DeployStatus `json:"status,omitempty"`

	// VpcEndpoint VPC endpoint configuration if available
	VpcEndpoint *map[string]interface{} `json:"vpcEndpoint"`
}

// ServiceCreate defines model for ServiceCreate.
type ServiceCreate struct {
	// Addons List of addons to enable for the service. 'time-series' enables TimescaleDB, 'ai' enables AI/vector extensions.
	Addons *[]ServiceCreateAddons `json:"addons,omitempty"`

	// CpuMillis The initial CPU allocation in milli-cores, or 'shared' for a shared-resource service.
	CpuMillis *string `json:"cpu_millis,omitempty"`

	// EnvironmentTag The environment tag for the service.
	EnvironmentTag *EnvironmentTag `json:"environment_tag,omitempty"`

	// MemoryGbs The initial memory allocation in gigabytes, or 'shared' for a shared-resource service.
	MemoryGbs *string `json:"memory_gbs,omitempty"`

	// Name A human-readable name for the service.
	Name string `json:"name"`

	// RegionCode The region where the service will be created. If not provided, we'll choose the best region for you.
	RegionCode *string `json:"region_code,omitempty"`

	// ReplicaCount Number of high-availability replicas to create (all replicas are asynchronous by default).
	ReplicaCount *int `json:"replica_count,omitempty"`
}

// ServiceCreateAddons defines model for ServiceCreate.Addons.
type ServiceCreateAddons string

// ServiceType defines model for ServiceType.
type ServiceType string

// ServiceVPCInput defines model for ServiceVPCInput.
type ServiceVPCInput struct {
	// VpcId The ID of the VPC to attach the service to.
	VpcId string `json:"vpc_id"`
}

// SetEnvironmentInput defines model for SetEnvironmentInput.
type SetEnvironmentInput struct {
	// Environment The target environment for the service.
	Environment SetEnvironmentInputEnvironment `json:"environment"`
}

// SetEnvironmentInputEnvironment The target environment for the service.
type SetEnvironmentInputEnvironment string

// SetHAReplicaInput At least one of sync_replica_count or replica_count must be provided.
type SetHAReplicaInput struct {
	// ReplicaCount Number of high-availability replicas (all replicas are asynchronous by default).
	ReplicaCount *int `json:"replica_count,omitempty"`

	// SyncReplicaCount Number of synchronous high-availability replicas.
	SyncReplicaCount *int `json:"sync_replica_count,omitempty"`
}

// TableIdentifier defines model for TableIdentifier.
type TableIdentifier struct {
	// SchemaName PostgreSQL schema name. Defaults to 'public' if not specified.
	SchemaName *string `json:"schema_name,omitempty"`

	// TableName PostgreSQL table name.
	TableName string `json:"table_name"`
}

// UpdateFileImportInput defines model for UpdateFileImportInput.
type UpdateFileImportInput struct {
	// Requests List of update operations to perform.
	Requests []UpdateFileImportRequest `json:"requests"`
}

// UpdateFileImportRequest Update request. Only one of cancel or labels should be set based on type.
type UpdateFileImportRequest struct {
	Cancel *UpdateFileImportRequestCancel `json:"cancel,omitempty"`
	Labels *UpdateFileImportRequestLabels `json:"labels,omitempty"`

	// Type Type of update operation to perform.
	Type UpdateFileImportRequestType `json:"type"`
}

// UpdateFileImportRequestCancel defines model for UpdateFileImportRequestCancel.
type UpdateFileImportRequestCancel struct {
	// Reason Reason for cancellation.
	Reason string `json:"reason"`
}

// UpdateFileImportRequestLabels defines model for UpdateFileImportRequestLabels.
type UpdateFileImportRequestLabels struct {
	// Labels New labels to set.
	Labels []FileImportLabel `json:"labels"`
}

// UpdateFileImportRequestType Type of update operation to perform.
type UpdateFileImportRequestType string

// UpdatePasswordInput defines model for UpdatePasswordInput.
type UpdatePasswordInput struct {
	// Password The new password.
	Password string `json:"password"`
}

// VPC defines model for VPC.
type VPC struct {
	Cidr       *string `json:"cidr,omitempty"`
	Id         *string `json:"id,omitempty"`
	Name       *string `json:"name,omitempty"`
	RegionCode *string `json:"region_code,omitempty"`
}

// VPCCreate defines model for VPCCreate.
type VPCCreate struct {
	Cidr       string `json:"cidr"`
	Name       string `json:"name"`
	RegionCode string `json:"region_code"`
}

// VPCRename defines model for VPCRename.
type VPCRename struct {
	// Name The new name for the VPC.
	Name string `json:"name"`
}

// FileImportId defines model for FileImportId.
type FileImportId = string

// PeeringId defines model for PeeringId.
type PeeringId = string

// ProjectId defines model for ProjectId.
type ProjectId = string

// ReplicaSetId defines model for ReplicaSetId.
type ReplicaSetId = string

// ServiceId defines model for ServiceId.
type ServiceId = string

// VPCId defines model for VPCId.
type VPCId = string

// AnalyticsResponse defines model for AnalyticsResponse.
type AnalyticsResponse struct {
	// Status Status of the analytics operation
	Status *string `json:"status,omitempty"`
}

// ClientError defines model for ClientError.
type ClientError = Error

// SuccessMessage defines model for SuccessMessage.
type SuccessMessage struct {
	Message *string `json:"message,omitempty"`
}

// PostAnalyticsIdentifyJSONBody defines parameters for PostAnalyticsIdentify.
type PostAnalyticsIdentifyJSONBody struct {
	// Properties Optional map of arbitrary properties associated with the user
	Properties *map[string]interface{} `json:"properties,omitempty"`
}

// PostAnalyticsTrackJSONBody defines parameters for PostAnalyticsTrack.
type PostAnalyticsTrackJSONBody struct {
	// Event The name of the event to track
	Event string `json:"event"`

	// Properties Optional map of arbitrary properties associated with the event
	Properties *map[string]interface{} `json:"properties,omitempty"`
}

// GetProjectsProjectIdServicesServiceIdFileimportsParams defines parameters for GetProjectsProjectIdServicesServiceIdFileimports.
type GetProjectsProjectIdServicesServiceIdFileimportsParams struct {
	// First Number of items to fetch for forward pagination.
	First *int `form:"first,omitempty" json:"first,omitempty"`

	// Last Number of items to fetch for backward pagination.
	Last *int `form:"last,omitempty" json:"last,omitempty"`

	// After Cursor for fetching the next page.
	After *string `form:"after,omitempty" json:"after,omitempty"`

	// Before Cursor for fetching the previous page.
	Before *string `form:"before,omitempty" json:"before,omitempty"`

	// LabelSelector Filter by label key and value using k8s label selector syntax (e.g., 'source=s3-live-sync,s3-live-sync-id=123').
	LabelSelector *string `form:"label_selector,omitempty" json:"label_selector,omitempty"`

	// States Filter by import states (comma-separated). Valid states are:
	// - IN_QUEUE: Import is queued for processing
	// - RUNNING: Import is currently processing
	// - RETRYING: Import is being retried after a failure
	// - SUCCESS: Import completed successfully
	// - FAILURE: Import failed
	// - CANCELLED: Import was cancelled
	// - PAUSED: Import is paused
	// - SKIPPED: Import was skipped
	States *string `form:"states,omitempty" json:"states,omitempty"`

	// S3KeyPrefix Filter S3 imports by key prefix (e.g., 'data/2024/'). Only affects S3 source imports.
	S3KeyPrefix *string `form:"s3_key_prefix,omitempty" json:"s3_key_prefix,omitempty"`

	// SourceType Filter by source type for optimized ordering. Supported values are S3, HTTP, INTERNAL.
	SourceType *GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceType `form:"source_type,omitempty" json:"source_type,omitempty"`
}

// GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceType defines parameters for GetProjectsProjectIdServicesServiceIdFileimports.
type GetProjectsProjectIdServicesServiceIdFileimportsParamsSourceType string

// PostAnalyticsIdentifyJSONRequestBody defines body for PostAnalyticsIdentify for application/json ContentType.
type PostAnalyticsIdentifyJSONRequestBody PostAnalyticsIdentifyJSONBody

// PostAnalyticsTrackJSONRequestBody defines body for PostAnalyticsTrack for application/json ContentType.
type PostAnalyticsTrackJSONRequestBody PostAnalyticsTrackJSONBody

// PostProjectsProjectIdServicesJSONRequestBody defines body for PostProjectsProjectIdServices for application/json ContentType.
type PostProjectsProjectIdServicesJSONRequestBody = ServiceCreate

// PostProjectsProjectIdServicesServiceIdAttachToVPCJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdAttachToVPC for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdAttachToVPCJSONRequestBody = ServiceVPCInput

// PostProjectsProjectIdServicesServiceIdDetachFromVPCJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdDetachFromVPC for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdDetachFromVPCJSONRequestBody = ServiceVPCInput

// PostProjectsProjectIdServicesServiceIdFileimportsJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdFileimports for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdFileimportsJSONRequestBody = CreateFileImportInput

// PostProjectsProjectIdServicesServiceIdFileimportsPresignedUrlJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdFileimportsPresignedUrl for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdFileimportsPresignedUrlJSONRequestBody = GeneratePresignedURLInput

// PatchProjectsProjectIdServicesServiceIdFileimportsImportIdJSONRequestBody defines body for PatchProjectsProjectIdServicesServiceIdFileimportsImportId for application/json ContentType.
type PatchProjectsProjectIdServicesServiceIdFileimportsImportIdJSONRequestBody = UpdateFileImportInput

// PostProjectsProjectIdServicesServiceIdForkServiceJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdForkService for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdForkServiceJSONRequestBody = ForkServiceCreate

// PostProjectsProjectIdServicesServiceIdReplicaSetsJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdReplicaSets for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdReplicaSetsJSONRequestBody = ReadReplicaSetCreate

// PostProjectsProjectIdServicesServiceIdReplicaSetsReplicaSetIdResizeJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdReplicaSetsReplicaSetIdResize for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdReplicaSetsReplicaSetIdResizeJSONRequestBody = ResizeInput

// PostProjectsProjectIdServicesServiceIdReplicaSetsReplicaSetIdSetEnvironmentJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdReplicaSetsReplicaSetIdSetEnvironment for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdReplicaSetsReplicaSetIdSetEnvironmentJSONRequestBody = SetEnvironmentInput

// PostProjectsProjectIdServicesServiceIdResizeJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdResize for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdResizeJSONRequestBody = ResizeInput

// PostProjectsProjectIdServicesServiceIdSetEnvironmentJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdSetEnvironment for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdSetEnvironmentJSONRequestBody = SetEnvironmentInput

// PostProjectsProjectIdServicesServiceIdSetHAJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdSetHA for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdSetHAJSONRequestBody = SetHAReplicaInput

// PostProjectsProjectIdServicesServiceIdUpdatePasswordJSONRequestBody defines body for PostProjectsProjectIdServicesServiceIdUpdatePassword for application/json ContentType.
type PostProjectsProjectIdServicesServiceIdUpdatePasswordJSONRequestBody = UpdatePasswordInput

// PostProjectsProjectIdVpcsJSONRequestBody defines body for PostProjectsProjectIdVpcs for application/json ContentType.
type PostProjectsProjectIdVpcsJSONRequestBody = VPCCreate

// PostProjectsProjectIdVpcsVpcIdPeeringsJSONRequestBody defines body for PostProjectsProjectIdVpcsVpcIdPeerings for application/json ContentType.
type PostProjectsProjectIdVpcsVpcIdPeeringsJSONRequestBody = PeeringCreate

// PostProjectsProjectIdVpcsVpcIdRenameJSONRequestBody defines body for PostProjectsProjectIdVpcsVpcIdRename for application/json ContentType.
type PostProjectsProjectIdVpcsVpcIdRenameJSONRequestBody = VPCRename
