# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

project_name: tiger-cli

builds:
  - main: ./cmd/tiger
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64

archives:
  - id: archive
    formats: [tar.gz]

    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    files:
      - README.md
      - LICENSE
      - NOTICE

# Linux package configuration (APT, RPM, etc.)
nfpms:
  - id: packages
    package_name: tiger-cli
    vendor: Timescale, Inc., d/b/a TigerData
    homepage: https://github.com/timescale/tiger-cli
    maintainer: TigerData <support@tigerdata.com>
    description: |-
      Tiger CLI - TigerData Cloud Platform CLI
      Command-line interface for managing TigerData Cloud Platform resources
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    priority: extra
    file_name_template: "{{ .ConventionalFileName }}"
    rpm:
      group: Unspecified
    deb:
      lintian_overrides:
        - statically-linked-binary

# Homebrew cask configuration
homebrew_casks:
  - name: tiger-cli

    repository:
      owner: timescale
      name: homebrew-tap
      # TODO: Token with permission to write to homebrew-tap repo
      # See: https://goreleaser.com/errors/resource-not-accessible-by-integration
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/timescale/tiger-cli
    description: |-
      Tiger CLI - TigerData Cloud Platform CLI
      Command-line interface for managing TigerData Cloud Platform resources
    binary: tiger
    license: Apache-2.0
    hooks:
      # TODO: Sign and notarize instead of removing quarantine bit
      # See: https://goreleaser.com/customization/homebrew_casks/#signing-and-notarizing
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiger"]
          end
    # Optional: Add caveats for user instructions
    caveats: |
      Tiger CLI has been installed successfully!

      Get started with:
        tiger auth login

      For help:
        tiger --help

changelog:
  sort: asc
  filters:
    exclude:
      - "^specs:"
      # TODO: Other files that should be ignored

# Release configuration
release:
  github:
    owner: timescale
    name: tiger-cli
  draft: false
  prerelease: auto
  name_template: "Release {{ .Tag }}"
