// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthInfoType.
const (
	AuthInfoTypeAPIKey AuthInfoType = "apiKey"
	AuthInfoTypeOauth  AuthInfoType = "oauth"
)

// Valid indicates whether the value is a known member of the AuthInfoType enum.
func (e AuthInfoType) Valid() bool {
	switch e {
	case AuthInfoTypeAPIKey:
		return true
	case AuthInfoTypeOauth:
		return true
	default:
		return false
	}
}

// Defines values for BackupCopyStatus.
const (
	BackupCopyStatusFAILED    BackupCopyStatus = "FAILED"
	BackupCopyStatusFINISHED  BackupCopyStatus = "FINISHED"
	BackupCopyStatusRETRYING  BackupCopyStatus = "RETRYING"
	BackupCopyStatusRUNNING   BackupCopyStatus = "RUNNING"
	BackupCopyStatusSCHEDULED BackupCopyStatus = "SCHEDULED"
	BackupCopyStatusUNKNOWN   BackupCopyStatus = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the BackupCopyStatus enum.
func (e BackupCopyStatus) Valid() bool {
	switch e {
	case BackupCopyStatusFAILED:
		return true
	case BackupCopyStatusFINISHED:
		return true
	case BackupCopyStatusRETRYING:
		return true
	case BackupCopyStatusRUNNING:
		return true
	case BackupCopyStatusSCHEDULED:
		return true
	case BackupCopyStatusUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for BackupType.
const (
	BackupTypeFULL        BackupType = "FULL"
	BackupTypeINCREMENTAL BackupType = "INCREMENTAL"
	BackupTypeUNKNOWN     BackupType = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the BackupType enum.
func (e BackupType) Valid() bool {
	switch e {
	case BackupTypeFULL:
		return true
	case BackupTypeINCREMENTAL:
		return true
	case BackupTypeUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for DeployStatus.
const (
	DeployStatusCONFIGURING DeployStatus = "CONFIGURING"
	DeployStatusDELETED     DeployStatus = "DELETED"
	DeployStatusDELETING    DeployStatus = "DELETING"
	DeployStatusOPTIMIZING  DeployStatus = "OPTIMIZING"
	DeployStatusPAUSED      DeployStatus = "PAUSED"
	DeployStatusPAUSING     DeployStatus = "PAUSING"
	DeployStatusQUEUED      DeployStatus = "QUEUED"
	DeployStatusREADY       DeployStatus = "READY"
	DeployStatusRESUMING    DeployStatus = "RESUMING"
	DeployStatusUNSTABLE    DeployStatus = "UNSTABLE"
	DeployStatusUPGRADING   DeployStatus = "UPGRADING"
)

// Valid indicates whether the value is a known member of the DeployStatus enum.
func (e DeployStatus) Valid() bool {
	switch e {
	case DeployStatusCONFIGURING:
		return true
	case DeployStatusDELETED:
		return true
	case DeployStatusDELETING:
		return true
	case DeployStatusOPTIMIZING:
		return true
	case DeployStatusPAUSED:
		return true
	case DeployStatusPAUSING:
		return true
	case DeployStatusQUEUED:
		return true
	case DeployStatusREADY:
		return true
	case DeployStatusRESUMING:
		return true
	case DeployStatusUNSTABLE:
		return true
	case DeployStatusUPGRADING:
		return true
	default:
		return false
	}
}

// Defines values for EnvironmentTag.
const (
	EnvironmentTagDEV  EnvironmentTag = "DEV"
	EnvironmentTagPROD EnvironmentTag = "PROD"
)

// Valid indicates whether the value is a known member of the EnvironmentTag enum.
func (e EnvironmentTag) Valid() bool {
	switch e {
	case EnvironmentTagDEV:
		return true
	case EnvironmentTagPROD:
		return true
	default:
		return false
	}
}

// Defines values for ForkStrategy.
const (
	ForkStrategyLASTSNAPSHOT ForkStrategy = "LAST_SNAPSHOT"
	ForkStrategyNOW          ForkStrategy = "NOW"
	ForkStrategyPITR         ForkStrategy = "PITR"
)

// Valid indicates whether the value is a known member of the ForkStrategy enum.
func (e ForkStrategy) Valid() bool {
	switch e {
	case ForkStrategyLASTSNAPSHOT:
		return true
	case ForkStrategyNOW:
		return true
	case ForkStrategyPITR:
		return true
	default:
		return false
	}
}

// Defines values for MetricsSeriesRequestFn.
const (
	MetricsSeriesRequestFnAVG      MetricsSeriesRequestFn = "AVG"
	MetricsSeriesRequestFnCOUNT    MetricsSeriesRequestFn = "COUNT"
	MetricsSeriesRequestFnINCREASE MetricsSeriesRequestFn = "INCREASE"
	MetricsSeriesRequestFnLAST     MetricsSeriesRequestFn = "LAST"
	MetricsSeriesRequestFnMAX      MetricsSeriesRequestFn = "MAX"
	MetricsSeriesRequestFnMIN      MetricsSeriesRequestFn = "MIN"
	MetricsSeriesRequestFnP50      MetricsSeriesRequestFn = "P50"
	MetricsSeriesRequestFnP90      MetricsSeriesRequestFn = "P90"
	MetricsSeriesRequestFnP99      MetricsSeriesRequestFn = "P99"
	MetricsSeriesRequestFnRATE     MetricsSeriesRequestFn = "RATE"
	MetricsSeriesRequestFnSUM      MetricsSeriesRequestFn = "SUM"
)

// Valid indicates whether the value is a known member of the MetricsSeriesRequestFn enum.
func (e MetricsSeriesRequestFn) Valid() bool {
	switch e {
	case MetricsSeriesRequestFnAVG:
		return true
	case MetricsSeriesRequestFnCOUNT:
		return true
	case MetricsSeriesRequestFnINCREASE:
		return true
	case MetricsSeriesRequestFnLAST:
		return true
	case MetricsSeriesRequestFnMAX:
		return true
	case MetricsSeriesRequestFnMIN:
		return true
	case MetricsSeriesRequestFnP50:
		return true
	case MetricsSeriesRequestFnP90:
		return true
	case MetricsSeriesRequestFnP99:
		return true
	case MetricsSeriesRequestFnRATE:
		return true
	case MetricsSeriesRequestFnSUM:
		return true
	default:
		return false
	}
}

// Defines values for ReadReplicaSetStatus.
const (
	ReadReplicaSetStatusActive   ReadReplicaSetStatus = "active"
	ReadReplicaSetStatusCreating ReadReplicaSetStatus = "creating"
	ReadReplicaSetStatusDeleting ReadReplicaSetStatus = "deleting"
	ReadReplicaSetStatusError    ReadReplicaSetStatus = "error"
	ReadReplicaSetStatusResizing ReadReplicaSetStatus = "resizing"
)

// Valid indicates whether the value is a known member of the ReadReplicaSetStatus enum.
func (e ReadReplicaSetStatus) Valid() bool {
	switch e {
	case ReadReplicaSetStatusActive:
		return true
	case ReadReplicaSetStatusCreating:
		return true
	case ReadReplicaSetStatusDeleting:
		return true
	case ReadReplicaSetStatusError:
		return true
	case ReadReplicaSetStatusResizing:
		return true
	default:
		return false
	}
}

// Defines values for ServiceCreateAddons.
const (
	ServiceCreateAddonsAi         ServiceCreateAddons = "ai"
	ServiceCreateAddonsTimeSeries ServiceCreateAddons = "time-series"
)

// Valid indicates whether the value is a known member of the ServiceCreateAddons enum.
func (e ServiceCreateAddons) Valid() bool {
	switch e {
	case ServiceCreateAddonsAi:
		return true
	case ServiceCreateAddonsTimeSeries:
		return true
	default:
		return false
	}
}

// Defines values for ServiceType.
const (
	ServiceTypePOSTGRES    ServiceType = "POSTGRES"
	ServiceTypeTIMESCALEDB ServiceType = "TIMESCALEDB"
	ServiceTypeVECTOR      ServiceType = "VECTOR"
)

// Valid indicates whether the value is a known member of the ServiceType enum.
func (e ServiceType) Valid() bool {
	switch e {
	case ServiceTypePOSTGRES:
		return true
	case ServiceTypeTIMESCALEDB:
		return true
	case ServiceTypeVECTOR:
		return true
	default:
		return false
	}
}

// Defines values for SetEnvironmentInputEnvironment.
const (
	SetEnvironmentInputEnvironmentDEV  SetEnvironmentInputEnvironment = "DEV"
	SetEnvironmentInputEnvironmentPROD SetEnvironmentInputEnvironment = "PROD"
)

// Valid indicates whether the value is a known member of the SetEnvironmentInputEnvironment enum.
func (e SetEnvironmentInputEnvironment) Valid() bool {
	switch e {
	case SetEnvironmentInputEnvironmentDEV:
		return true
	case SetEnvironmentInputEnvironmentPROD:
		return true
	default:
		return false
	}
}

// AuthInfo Information about the authentication credentials being used. Exactly one
// of `api_key` or `oauth` is populated; the `type` field discriminates.
type AuthInfo struct {
	// APIKeyDeprecated Deprecated. Use `api_key` instead.
	// Deprecated: Use `api_key` instead.
	APIKeyDeprecated *AuthInfoAPIKey `json:"apiKey,omitempty"`

	// APIKey Information about the API key credentials (PAT).
	APIKey *AuthInfoAPIKey `json:"api_key,omitempty"`

	// Oauth OAuth user details. Present for OAuth user callers.
	Oauth *AuthInfoOAuth `json:"oauth,omitempty"`

	// Type Discriminator for the credential shape. `apiKey` for PAT callers; `oauth` for OAuth
	// user callers.
	//
	//
	// Example: apiKey
	Type AuthInfoType `json:"type"`
}

// AuthInfoType Discriminator for the credential shape. `apiKey` for PAT callers; `oauth` for OAuth
// user callers.
//
// Example: apiKey
type AuthInfoType string

// AuthInfoAPIKey Information about the API key credentials (PAT).
type AuthInfoAPIKey struct {
	// Created When the client credentials were created.
	//
	// Example: 2024-01-15T10:30:00Z
	Created time.Time `json:"created"`

	// IssuingUser Information about the user who created the credentials.
	IssuingUser AuthInfoIssuingUser `json:"issuing_user"`

	// Name The name of the credential.
	//
	// Example: my-production-token
	Name string `json:"name"`

	// Project Information about the project.
	Project AuthInfoProject `json:"project"`

	// PublicKey The public key of the client credentials.
	//
	// Example: tskey_abc123
	PublicKey string `json:"public_key"`
}

// AuthInfoIssuingUser Information about the user who created the credentials.
type AuthInfoIssuingUser struct {
	// Email The user's email.
	//
	// Example: john.doe@example.com
	Email openapi_types.Email `json:"email"`

	// ID The user ID.
	//
	// Example: user123
	ID string `json:"id"`

	// Name The user's name.
	//
	// Example: John Doe
	Name string `json:"name"`
}

// AuthInfoOAuth OAuth user details. Present for OAuth user callers.
type AuthInfoOAuth struct {
	// User The authenticated OAuth user.
	User AuthInfoUser `json:"user"`
}

// AuthInfoProject Information about the project.
type AuthInfoProject struct {
	// ID The project ID.
	//
	// Example: rp1pz7uyae
	ID string `json:"id"`

	// Name The name of the project.
	//
	// Example: My Production Project
	Name string `json:"name"`

	// PlanType The plan type for the project.
	//
	// Example: FREE
	PlanType string `json:"plan_type"`
}

// AuthInfoUser The authenticated OAuth user.
type AuthInfoUser struct {
	// Email The user's email.
	//
	// Example: john.doe@example.com
	Email openapi_types.Email `json:"email"`

	// ID The numeric user ID.
	//
	// Example: 1234567
	ID string `json:"id"`

	// Name The user's name.
	//
	// Example: John Doe
	Name string `json:"name"`
}

// Backup A single backup of a service, taken automatically by Tiger Cloud.
type Backup struct {
	// DurationSeconds How long the backup took, in seconds. Absent while the backup is still running.
	//
	// Example: 672
	DurationSeconds *int64 `json:"duration_seconds,omitempty"`

	// FinishedAt When the backup finished. Absent while the backup is still running.
	//
	// Example: 2026-01-15T09:41:12Z
	FinishedAt *time.Time `json:"finished_at,omitempty"`

	// Label The label the backup system assigns to this backup.
	//
	// Example: 20260115-093000F
	Label string `json:"label"`

	// Regions Every region storing a copy of this backup: the region the service
	// runs in, plus any region enabled for cross-region backups.
	Regions []BackupRegionState `json:"regions"`

	// SizeBytes The size of the backup in bytes. Absent while the backup is still running.
	//
	// Example: 4831838208
	SizeBytes *int64 `json:"size_bytes,omitempty"`

	// StartedAt When the backup started.
	//
	// Example: 2026-01-15T09:30:00Z
	StartedAt time.Time `json:"started_at"`

	// Type The type of the backup.
	Type BackupType `json:"type"`
}

// BackupCopyStatus The state of a copy of a backup in one region.
//
// - `SCHEDULED`: the copy has not started yet.
// - `RUNNING`: the copy is in progress.
// - `RETRYING`: the copy failed and is being retried.
// - `FINISHED`: the copy completed successfully.
// - `FAILED`: the copy did not complete.
// - `UNKNOWN`: an unrecognized state.
type BackupCopyStatus string

// BackupRegionState A region storing a copy of a backup.
type BackupRegionState struct {
	// RegionCode The region storing the copy.
	//
	// Example: eu-central-1
	RegionCode string `json:"region_code"`

	// Status The state of this copy.
	Status *BackupCopyStatus `json:"status,omitempty"`
}

// BackupType The type of a backup.
//
// - `FULL`: a complete copy of the service's data.
// - `INCREMENTAL`: only the data that changed since the previous backup.
// - `UNKNOWN`: a type this version of the API does not name.
type BackupType string

// ConnectionPooler Connection pooler configuration for a service.
type ConnectionPooler struct {
	// Endpoint A network endpoint for connecting to a service.
	Endpoint *Endpoint `json:"endpoint,omitempty"`
}

// DeployStatus The current deployment status of the service:
// - QUEUED: the create request has been submitted and is queued
// - DELETING: the service is being deleted
// - CONFIGURING: the service is up but still completing configuration
// - READY: fully configured and serving traffic
// - DELETED: the service has been deleted
// - UNSTABLE: the service was ready but is not currently reachable
// - PAUSING: the service is being paused
// - PAUSED: the service is paused (temporarily shut down)
// - RESUMING: the service is resuming after being paused
// - UPGRADING: the service is being updated
//
// OPTIMIZING is deprecated and should not be used.
type DeployStatus string

// Endpoint A network endpoint for connecting to a service.
type Endpoint struct {
	// Host The hostname of the endpoint.
	//
	// Example: i4wmp4crev.oec7sxsza2.tsdb.cloud.timescale.com
	Host *string `json:"host,omitempty"`

	// Port The port of the endpoint.
	//
	// Example: 32625
	Port *int `json:"port,omitempty"`
}

// EnvironmentTag The environment tag for the service:
// - DEV: a development environment
// - PROD: a production environment
type EnvironmentTag string

// Error An error returned when a request cannot be completed.
type Error struct {
	// Code A machine-readable error code.
	//
	// Example: NOT_FOUND
	Code *string `json:"code,omitempty"`

	// Message A human-readable error message.
	//
	// Example: The requested service could not be found.
	Message *string `json:"message,omitempty"`
}

// ForkServiceCreate Create a fork of an existing service. Service type, region code, and storage are always inherited from the parent service.
// HA replica count is always set to 0 for forked services.
type ForkServiceCreate struct {
	// CPUMillis The initial CPU allocation in milli-cores, or 'shared' for a shared-resource service. If not provided, will inherit from parent service.
	//
	// Example: 1000
	CPUMillis *string `json:"cpu_millis,omitempty"`

	// EnvironmentTag The environment tag for the forked service.
	EnvironmentTag *EnvironmentTag `json:"environment_tag,omitempty"`

	// ForkStrategy Strategy for creating the fork:
	// - LAST_SNAPSHOT: Use existing snapshot for fast fork
	// - NOW: Create new snapshot for up-to-date fork
	// - PITR: Point-in-time recovery using target_time
	ForkStrategy ForkStrategy `json:"fork_strategy"`

	// MemoryGbs The initial memory allocation in gigabytes, or 'shared' for a shared-resource service. If not provided, will inherit from parent service.
	//
	// Example: 4
	MemoryGbs *string `json:"memory_gbs,omitempty"`

	// Name A human-readable name for the forked service. If not provided, will use parent service name with "-fork" suffix.
	//
	// Example: my-production-db-fork
	Name *string `json:"name,omitempty"`

	// TargetTime Target time for point-in-time recovery. Required when fork_strategy is PITR.
	//
	// Example: 2024-01-01T00:00:00Z
	TargetTime *time.Time `json:"target_time,omitempty"`
}

// ForkSpec The service this service was forked from.
type ForkSpec struct {
	// IsStandby Whether this service is a standby of the parent service.
	//
	// Example: false
	IsStandby *bool `json:"is_standby,omitempty"`

	// ProjectID The project of the parent service.
	//
	// Example: rp1pz7uyae
	ProjectID *string `json:"project_id,omitempty"`

	// ServiceID The ID of the parent service.
	//
	// Example: kd9w2xp4mz
	ServiceID *string `json:"service_id,omitempty"`
}

// ForkStrategy Strategy for creating the fork:
// - LAST_SNAPSHOT: Use existing snapshot for fast fork
// - NOW: Create new snapshot for up-to-date fork
// - PITR: Point-in-time recovery using target_time
type ForkStrategy string

// HAReplica High-availability replica configuration for a service.
type HAReplica struct {
	// ReplicaCount Number of high-availability replicas (all replicas are asynchronous by default).
	//
	// Example: 1
	ReplicaCount *int `json:"replica_count,omitempty"`

	// SyncReplicaCount Number of synchronous high-availability replicas.
	//
	// Example: 1
	SyncReplicaCount *int `json:"sync_replica_count,omitempty"`
}

// MetricDataPoint A single time/value pair within a MetricSeries.
type MetricDataPoint struct {
	// Time The bucket start timestamp.
	//
	// Example: 2026-06-25T10:00:00Z
	Time time.Time `json:"time"`

	// Value The aggregated value at this bucket, or null for a gap bucket with
	// no collected data. Gap buckets are still emitted (one entry per
	// bucket in the window), so this is null rather than omitted.
	//
	//
	// Example: 247.5
	Value *float64 `json:"value"`
}

// MetricLabelFilter A single key/value label match applied to a metric series query.
type MetricLabelFilter struct {
	// Key Label key to match against, e.g. `role` or `job_id`.
	//
	// Example: role
	Key string `json:"key"`

	// Value Label value to match. Case sensitivity follows the underlying metric's storage convention.
	//
	// Example: primary
	Value string `json:"value"`
}

// MetricSeries One labeled time series — the label set plus its per-bucket data points.
type MetricSeries struct {
	// Data Per-bucket data points for this label set.
	Data []MetricDataPoint `json:"data"`

	// Labels Label set identifying this series. The key set depends on the
	// metric (e.g. `role`, `ordinal`).
	Labels map[string]string `json:"labels"`
}

// MetricsSeriesRequest Parameters for a single getServiceMetricsSeries query. Sent as a JSON
// body so callers can pass an unbounded filter set without query-string
// length pressure.
type MetricsSeriesRequest struct {
	// BucketSeconds Aggregation bucket size in seconds. Optional: when omitted the
	// server picks a default that matches the window (roughly 1m for
	// windows up to 1h, 1h for up to 30d, 1d beyond that). Minimum is
	// 60s (finer buckets don't add resolution given scrape intervals).
	// Must be coarse enough for the window's tier; requests that ask
	// for a finer bucket than the tier can produce are rejected.
	//
	//
	// Example: 3600
	BucketSeconds *int `json:"bucket_seconds,omitempty"`

	// Filters Label filters applied to the series query. Recognized label names
	// depend on the metric. The most common is `role` (value `primary` or
	// `replica`). When `role` is omitted, some metrics default to primary
	// and others return data for all roles (one series per role); pass an
	// explicit role for deterministic results. Role label values in the
	// response are lowercased.
	Filters *[]MetricLabelFilter `json:"filters,omitempty"`

	// Fn Aggregation function applied to raw/pre-aggregated samples when
	// collapsing them into one value per output bucket. Optional: when
	// omitted the server picks the default for the metric (currently
	// `LAST`).
	//
	// Not accepted on the following metrics — requests are rejected
	// with `INVALID_REQUEST`:
	//   - `timescale_cloud_system_cpu_total_millicores`
	//   - `timescale_cloud_system_cpu_usage_millicores`
	//   - `timescale_cloud_system_disk_io_read_bytes`
	//   - `timescale_cloud_system_disk_io_read_ops`
	//   - `timescale_cloud_system_disk_io_total_bytes`
	//   - `timescale_cloud_system_disk_io_total_ops`
	//   - `timescale_cloud_system_disk_io_write_bytes`
	//   - `timescale_cloud_system_disk_io_write_ops`
	//   - `timescale_cloud_system_disk_usage_bytes`
	//   - `timescale_cloud_system_memory_total_bytes`
	//   - `timescale_cloud_system_memory_usage_bytes`
	//   - `timescale_cloud_database_qps`
	//   - `timescale_cloud_database_num_connections`
	//   - `timescale_cloud_database_job_duration_usecs`
	//   - `timescale_cloud_database_job_success`
	//
	// Values:
	//   - `RATE`: counter-reset-aware per-second rate of change.
	//   - `INCREASE`: counter-reset-aware total increase over the bucket.
	//   - `SUM`: sum of samples in the bucket.
	//   - `AVG`: mean of samples in the bucket.
	//   - `MIN`: minimum sample in the bucket.
	//   - `MAX`: maximum sample in the bucket.
	//   - `COUNT`: number of samples in the bucket.
	//   - `P50` / `P90` / `P99`: percentile approximations (only valid
	//     for metrics stored as sketches).
	//   - `LAST`: the most recent sample in the bucket (default).
	//
	//
	// Example: RATE
	Fn *MetricsSeriesRequestFn `json:"fn,omitempty"`

	// From Start of the time window (RFC3339; nanosecond precision accepted).
	//
	// Example: 2026-06-25T10:00:00Z
	From time.Time `json:"from"`

	// Name Metric series name. Use getServiceMetricsAvailableSeries to discover valid values.
	//
	// Example: timescale_cloud_system_cpu_usage_millicores
	Name string `json:"name"`

	// To End of the time window (RFC3339; nanosecond precision accepted).
	//
	// Example: 2026-06-25T11:00:00Z
	To time.Time `json:"to"`
}

// MetricsSeriesRequestFn Aggregation function applied to raw/pre-aggregated samples when
// collapsing them into one value per output bucket. Optional: when
// omitted the server picks the default for the metric (currently
// `LAST`).
//
// Not accepted on the following metrics — requests are rejected
// with `INVALID_REQUEST`:
//   - `timescale_cloud_system_cpu_total_millicores`
//   - `timescale_cloud_system_cpu_usage_millicores`
//   - `timescale_cloud_system_disk_io_read_bytes`
//   - `timescale_cloud_system_disk_io_read_ops`
//   - `timescale_cloud_system_disk_io_total_bytes`
//   - `timescale_cloud_system_disk_io_total_ops`
//   - `timescale_cloud_system_disk_io_write_bytes`
//   - `timescale_cloud_system_disk_io_write_ops`
//   - `timescale_cloud_system_disk_usage_bytes`
//   - `timescale_cloud_system_memory_total_bytes`
//   - `timescale_cloud_system_memory_usage_bytes`
//   - `timescale_cloud_database_qps`
//   - `timescale_cloud_database_num_connections`
//   - `timescale_cloud_database_job_duration_usecs`
//   - `timescale_cloud_database_job_success`
//
// Values:
//   - `RATE`: counter-reset-aware per-second rate of change.
//   - `INCREASE`: counter-reset-aware total increase over the bucket.
//   - `SUM`: sum of samples in the bucket.
//   - `AVG`: mean of samples in the bucket.
//   - `MIN`: minimum sample in the bucket.
//   - `MAX`: maximum sample in the bucket.
//   - `COUNT`: number of samples in the bucket.
//   - `P50` / `P90` / `P99`: percentile approximations (only valid
//     for metrics stored as sketches).
//   - `LAST`: the most recent sample in the bucket (default).
//
// Example: RATE
type MetricsSeriesRequestFn string

// Peering A VPC peering connection to an external cloud account.
type Peering struct {
	// ErrorMessage A human-readable error message when the peering connection failed.
	//
	// Example: VPC not found
	ErrorMessage *string `json:"error_message,omitempty"`

	// ID The unique identifier for the peering connection.
	//
	// Example: 1234567890
	ID *string `json:"id,omitempty"`

	// PeerAccountID The cloud account ID of the peer VPC.
	//
	// Example: acc-12345
	PeerAccountID string `json:"peer_account_id"`

	// PeerRegionCode The cloud region of the peer VPC.
	//
	// Example: us-east-1
	PeerRegionCode string `json:"peer_region_code"`

	// PeerVpcID The ID of the peer VPC.
	//
	// Example: 1234567890
	PeerVpcID string `json:"peer_vpc_id"`

	// ProvisionedID The provider-assigned identifier for the provisioned peering.
	//
	// Example: 1234567890
	ProvisionedID *string `json:"provisioned_id,omitempty"`

	// Status The current status of the peering connection.
	//
	// Example: active
	Status *string `json:"status,omitempty"`
}

// PeeringCreate Parameters for creating a VPC peering connection.
type PeeringCreate struct {
	// PeerAccountID The cloud account ID of the peer VPC.
	//
	// Example: acc-12345
	PeerAccountID string `json:"peer_account_id"`

	// PeerRegionCode The cloud region of the peer VPC.
	//
	// Example: us-east-1
	PeerRegionCode string `json:"peer_region_code"`

	// PeerVpcID The ID of the peer VPC.
	//
	// Example: 1234567890
	PeerVpcID string `json:"peer_vpc_id"`
}

// Project A project that organizes your Tiger Cloud resources, such as services and VPCs.
type Project struct {
	// ID The unique identifier for the project.
	//
	// Example: rp1pz7uyae
	ID string `json:"id"`

	// Name The name of the project.
	//
	// Example: My Production Project
	Name string `json:"name"`
}

// ReadReplicaSet A set of read replicas for a service.
type ReadReplicaSet struct {
	// ConnectionPooler Connection pooler configuration for a service.
	ConnectionPooler *ConnectionPooler `json:"connection_pooler,omitempty"`

	// CPUMillis CPU allocation in milli-cores.
	//
	// Example: 250
	CPUMillis int `json:"cpu_millis"`

	// Endpoint A network endpoint for connecting to a service.
	Endpoint *Endpoint `json:"endpoint,omitempty"`

	// ID The unique identifier for the read replica set.
	//
	// Example: alb8jicdpr
	ID string `json:"id"`

	// MemoryGbs Memory allocation in gigabytes.
	//
	// Example: 1
	MemoryGbs int `json:"memory_gbs"`

	// Metadata Additional metadata for the read replica set.
	Metadata *ReplicaSetMetadata `json:"metadata,omitempty"`

	// Name The name of the read replica set.
	//
	// Example: reporting-replica-1
	Name string `json:"name"`

	// Nodes Number of nodes in the replica set.
	//
	// Example: 2
	Nodes int `json:"nodes"`

	// Status The current status of the read replica set:
	// - creating: the replica set is being provisioned
	// - active: the replica set is provisioned and serving traffic
	// - resizing: the replica set is being resized
	// - deleting: the replica set is being deleted
	// - error: the replica set is in an error state
	//
	//
	// Example: active
	Status ReadReplicaSetStatus `json:"status"`
}

// ReadReplicaSetStatus The current status of the read replica set:
// - creating: the replica set is being provisioned
// - active: the replica set is provisioned and serving traffic
// - resizing: the replica set is being resized
// - deleting: the replica set is being deleted
// - error: the replica set is in an error state
//
// Example: active
type ReadReplicaSetStatus string

// ReadReplicaSetCreate Parameters for creating a read replica set.
type ReadReplicaSetCreate struct {
	// CPUMillis The initial CPU allocation in milli-cores.
	//
	// Example: 250
	CPUMillis int `json:"cpu_millis"`

	// MemoryGbs The initial memory allocation in gigabytes.
	//
	// Example: 1
	MemoryGbs int `json:"memory_gbs"`

	// Name A human-readable name for the read replica.
	//
	// Example: my-reporting-replica
	Name string `json:"name"`

	// Nodes Number of nodes to create in the replica set.
	//
	// Example: 2
	Nodes int `json:"nodes"`
}

// ReplicaSetMetadata Additional metadata for the read replica set.
type ReplicaSetMetadata struct {
	// Environment Environment tag for the read replica set.
	//
	// Example: PROD
	Environment *string `json:"environment,omitempty"`
}

// ResizeInput Parameters for resizing a service.
type ResizeInput struct {
	// CPUMillis The new CPU allocation in milli-cores.
	//
	// Example: 1000
	CPUMillis string `json:"cpu_millis"`

	// MemoryGbs The new memory allocation in gigabytes.
	//
	// Example: 4
	MemoryGbs string `json:"memory_gbs"`
}

// Resource A resource allocated to the service.
type Resource struct {
	// ID Resource identifier.
	//
	// Example: n4ph2tqz8r
	ID *string `json:"id,omitempty"`

	// Spec Resource specification.
	Spec *ResourceSpec `json:"spec,omitempty"`
}

// ResourceSpec Resource specification.
type ResourceSpec struct {
	// CPUMillis CPU allocation in millicores.
	//
	// Example: 1000
	CPUMillis *int `json:"cpu_millis,omitempty"`

	// MemoryGbs Memory allocation in gigabytes.
	//
	// Example: 4
	MemoryGbs *int `json:"memory_gbs,omitempty"`

	// VolumeType Type of storage volume.
	//
	// Example: gp3
	VolumeType *string `json:"volume_type,omitempty"`
}

// Service A database service and its current configuration.
type Service struct {
	// ConnectionPooler Connection pooler configuration for a service.
	ConnectionPooler *ConnectionPooler `json:"connection_pooler,omitempty"`

	// Created Creation timestamp.
	//
	// Example: 2025-01-15T09:30:00Z
	Created time.Time `json:"created"`

	// Endpoint A network endpoint for connecting to a service.
	Endpoint *Endpoint `json:"endpoint,omitempty"`

	// ForkedFrom The service this service was forked from.
	ForkedFrom *ForkSpec `json:"forked_from,omitempty"`

	// HaReplicas High-availability replica configuration for a service.
	HaReplicas *HAReplica `json:"ha_replicas,omitempty"`

	// InitialPassword The initial password for the service.
	//
	// Example: a-very-secure-initial-password
	InitialPassword *string `json:"initial_password,omitempty"`

	// Metadata Additional metadata for the service.
	Metadata *ServiceMetadata `json:"metadata,omitempty"`

	// Metrics Resource usage metrics for the service.
	Metrics *ServiceMetrics `json:"metrics,omitempty"`

	// Name The name of the service.
	//
	// Example: my-production-db
	Name string `json:"name"`

	// ProjectID The project this service belongs to.
	//
	// Example: rp1pz7uyae
	ProjectID string `json:"project_id"`

	// ReadReplicaSets The read replica sets attached to the service.
	ReadReplicaSets *[]ReadReplicaSet `json:"read_replica_sets,omitempty"`

	// RegionCode The cloud region where the service is hosted.
	//
	// Example: us-east-1
	RegionCode string `json:"region_code"`

	// Resources List of resources allocated to the service.
	Resources []Resource `json:"resources"`

	// ServiceID The unique identifier for the service.
	//
	// Example: kd9w2xp4mz
	ServiceID string `json:"service_id"`

	// ServiceType The type of the service.
	ServiceType ServiceType `json:"service_type"`

	// Status Current status of the service.
	Status DeployStatus `json:"status"`

	// VpcEndpointDeprecated Deprecated. Use `vpc_endpoint` instead.
	// Deprecated: Use `vpc_endpoint` instead.
	VpcEndpointDeprecated *VPCEndpoint `json:"vpcEndpoint,omitempty"`

	// VpcEndpoint VPC endpoint configuration if available.
	VpcEndpoint *VPCEndpoint `json:"vpc_endpoint,omitempty"`
}

// ServiceCreate Parameters for creating a service.
type ServiceCreate struct {
	// Addons List of addons to enable for the service. 'time-series' enables TimescaleDB, 'ai' enables AI/vector extensions.
	//
	// Example: ["time-series","ai"]
	Addons *[]ServiceCreateAddons `json:"addons,omitempty"`

	// CPUMillis The initial CPU allocation in milli-cores, or 'shared' for a shared-resource service.
	//
	// Example: 1000
	CPUMillis *string `json:"cpu_millis,omitempty"`

	// EnvironmentTag The environment tag for the service.
	EnvironmentTag *EnvironmentTag `json:"environment_tag,omitempty"`

	// MemoryGbs The initial memory allocation in gigabytes, or 'shared' for a shared-resource service.
	//
	// Example: 4
	MemoryGbs *string `json:"memory_gbs,omitempty"`

	// Name A human-readable name for the service.
	//
	// Example: my-production-db
	Name string `json:"name"`

	// RegionCode The region where the service will be created. If not provided, we'll choose the best region for you.
	//
	// Example: us-east-1
	RegionCode *string `json:"region_code,omitempty"`

	// ReplicaCount Number of high-availability replicas to create (all replicas are asynchronous by default).
	//
	// Example: 2
	ReplicaCount *int `json:"replica_count,omitempty"`
}

// ServiceCreateAddons defines model for ServiceCreate.Addons.
type ServiceCreateAddons string

// ServiceLogEntry A single structured log entry from a service.
type ServiceLogEntry struct {
	// Message Log message text.
	//
	// Example: database system is ready to accept connections
	Message string `json:"message"`

	// Severity PostgreSQL severity level (e.g. LOG, WARNING, ERROR, FATAL).
	//
	// Example: LOG
	Severity string `json:"severity"`

	// Timestamp Timestamp of the log entry (RFC3339 format).
	//
	// Example: 2025-01-15T09:30:00Z
	Timestamp time.Time `json:"timestamp"`
}

// ServiceLogs The logs for a service.
type ServiceLogs struct {
	// Entries Structured log entries with timestamp and severity metadata.
	// Entries are in the same order as logs and can be used in place of it
	// by callers that need structured data.
	Entries *[]ServiceLogEntry `json:"entries,omitempty"`

	// LastCursorDeprecated Deprecated. Use `last_cursor` instead.
	//
	// Example: eyJ0cyI6IjIwMjUtMDEtMTVUMDk6MzA6MDBaIn0=
	// Deprecated: Use `last_cursor` instead.
	LastCursorDeprecated *string `json:"lastCursor,omitempty"`

	// LastCursor Opaque cursor for the next page of results. Present when more log entries
	// exist older than the last entry in this response. Pass this value as the
	// `cursor` query parameter to retrieve the next page. Absent when there are
	// no further results.
	//
	//
	// Example: eyJ0cyI6IjIwMjUtMDEtMTVUMDk6MzA6MDBaIn0=
	LastCursor *string `json:"last_cursor,omitempty"`

	// Logs Array of log message strings. Preserved for backwards compatibility.
	// Deprecated: Use `entries` instead.
	Logs []string `json:"logs"`
}

// ServiceMetadata Additional metadata for the service.
type ServiceMetadata struct {
	// Environment Environment tag for the service.
	//
	// Example: PROD
	Environment *string `json:"environment,omitempty"`
}

// ServiceMetrics Resource usage metrics for the service.
type ServiceMetrics struct {
	// MemoryMb Memory usage in megabytes.
	//
	// Example: 512
	MemoryMb *int `json:"memory_mb,omitempty"`

	// MilliCPU CPU usage in millicores.
	//
	// Example: 250
	MilliCPU *int `json:"milli_cpu,omitempty"`

	// StorageMb Storage usage in megabytes.
	//
	// Example: 1024
	StorageMb *int `json:"storage_mb,omitempty"`
}

// ServiceRename Parameters for renaming a service.
type ServiceRename struct {
	// Name The new name for the service.
	//
	// Example: my-renamed-service
	Name string `json:"name"`
}

// ServiceType The type of the service:
// - TIMESCALEDB: a TimescaleDB service (PostgreSQL with the TimescaleDB extension)
// - POSTGRES: a standard PostgreSQL service
//
// VECTOR is deprecated and should not be used.
type ServiceType string

// ServiceVPCInput Parameters for attaching a service to a VPC.
type ServiceVPCInput struct {
	// VpcID The ID of the VPC to attach the service to.
	//
	// Example: 1234567890
	VpcID string `json:"vpc_id"`
}

// SetEnvironmentInput Parameters for setting a service's environment.
//
// Example: {"environment":"PROD"}
type SetEnvironmentInput struct {
	// Environment The target environment for the service:
	// - PROD: a production environment
	// - DEV: a development environment
	Environment SetEnvironmentInputEnvironment `json:"environment"`
}

// SetEnvironmentInputEnvironment The target environment for the service:
// - PROD: a production environment
// - DEV: a development environment
type SetEnvironmentInputEnvironment string

// SetHAReplicaInput At least one of sync_replica_count or replica_count must be provided.
type SetHAReplicaInput struct {
	// ReplicaCount Number of high-availability replicas (all replicas are asynchronous by default).
	//
	// Example: 1
	ReplicaCount *int `json:"replica_count,omitempty"`

	// SyncReplicaCount Number of synchronous high-availability replicas.
	//
	// Example: 1
	SyncReplicaCount *int `json:"sync_replica_count,omitempty"`
}

// UpdatePasswordInput Parameters for updating a service's password.
type UpdatePasswordInput struct {
	// Password The new password.
	//
	// Example: a-very-secure-new-password
	Password string `json:"password"`
}

// VPC A virtual private cloud that services can be attached to.
type VPC struct {
	// Cidr The IPv4 CIDR block for the VPC, in address/prefix notation (e.g. 10.0.0.0/16).
	//
	// Example: 10.0.0.0/16
	Cidr string `json:"cidr"`

	// ID The unique identifier for the VPC.
	//
	// Example: 1234567890
	ID *string `json:"id,omitempty"`

	// Name The name of the VPC.
	//
	// Example: my-production-vpc
	Name string `json:"name"`

	// RegionCode The cloud region where the VPC is hosted.
	//
	// Example: us-east-1
	RegionCode string `json:"region_code"`
}

// VPCCreate Parameters for creating a VPC.
type VPCCreate struct {
	// Cidr The IPv4 CIDR block for the VPC, in address/prefix notation (e.g. 10.0.0.0/16).
	//
	// Example: 10.0.0.0/16
	Cidr string `json:"cidr"`

	// Name The name of the VPC.
	//
	// Example: my-production-vpc
	Name string `json:"name"`

	// RegionCode The cloud region where the VPC will be created.
	//
	// Example: us-east-1
	RegionCode string `json:"region_code"`
}

// VPCEndpoint VPC endpoint configuration for connecting to a service over VPC peering.
type VPCEndpoint struct {
	// Host The hostname for connecting to the service over VPC peering.
	//
	// Example: i4wmp4crev.oec7sxsza2.tsdb.cloud.timescale.com
	Host *string `json:"host,omitempty"`

	// Port The port for connecting to the service over VPC peering.
	//
	// Example: 5432
	Port *int `json:"port,omitempty"`

	// VpcID The ID of the VPC the endpoint is associated with.
	//
	// Example: 1337
	VpcID *string `json:"vpc_id,omitempty"`
}

// VPCRename Parameters for renaming a VPC.
type VPCRename struct {
	// Name The new name for the VPC.
	//
	// Example: my-renamed-vpc
	Name string `json:"name"`
}

// PeeringID Example: 1234567890
type PeeringID = string

// ProjectID Example: rp1pz7uyae
type ProjectID = string

// ReplicaSetID Example: alb8jicdpr
type ReplicaSetID = string

// ServiceID Example: d1k5vk7hf2
type ServiceID = string

// VPCId Example: 1234567890
type VPCId = string

// AnalyticsResponse defines model for AnalyticsResponse.
type AnalyticsResponse struct {
	// Status Status of the analytics operation.
	//
	// Example: success
	Status *string `json:"status,omitempty"`
}

// ClientError An error returned when a request cannot be completed.
type ClientError = Error

// SuccessMessage defines model for SuccessMessage.
type SuccessMessage struct {
	// Message Example: Action completed successfully.
	Message *string `json:"message,omitempty"`
}

// IdentifyUserJSONBody defines parameters for IdentifyUser.
type IdentifyUserJSONBody struct {
	// Properties Optional map of arbitrary properties associated with the user.
	//
	// Example: {"email":"user@example.com","name":"John Doe"}
	Properties *map[string]interface{} `json:"properties,omitempty"`
}

// TrackEventJSONBody defines parameters for TrackEvent.
type TrackEventJSONBody struct {
	// Event The name of the event to track.
	//
	// Example: service_created
	Event string `json:"event"`

	// Properties Optional map of arbitrary properties associated with the event.
	//
	// Example: {"region":"us-east-1"}
	Properties *map[string]interface{} `json:"properties,omitempty"`
}

// LogoutJSONBody defines parameters for Logout.
type LogoutJSONBody struct {
	// RefreshToken The OAuth refresh token to revoke. Omit for sessions without a refresh token.
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// GetServiceLogsParams defines parameters for GetServiceLogs.
type GetServiceLogsParams struct {
	// Node Specific service node to fetch logs from (for multi-node services).
	Node *int `form:"node,omitempty" json:"node,omitempty"`

	// Cursor Opaque pagination cursor returned as `last_cursor` in a previous response.
	// When provided, returns the next page of logs older than the cursor position.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Until Upper bound timestamp — fetch logs before this time (RFC3339 format, e.g., 2024-01-15T10:00:00Z).
	Until *time.Time `form:"until,omitempty" json:"until,omitempty"`

	// Since Lower bound timestamp — fetch logs after this time (RFC3339 format).
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Search Full-text search terms to filter log lines. Repeat the parameter for multiple values
	// (e.g. `?search=slow+query&search=ERROR`).
	Search *[]string `form:"search,omitempty" json:"search,omitempty"`

	// Severities Severity levels to filter results. Repeat the parameter for multiple values
	// (e.g. `?severities=ERROR&severities=WARNING`).
	Severities *[]string `form:"severities,omitempty" json:"severities,omitempty"`
}

// IdentifyUserJSONRequestBody defines body for IdentifyUser for application/json ContentType.
type IdentifyUserJSONRequestBody IdentifyUserJSONBody

// TrackEventJSONRequestBody defines body for TrackEvent for application/json ContentType.
type TrackEventJSONRequestBody TrackEventJSONBody

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody LogoutJSONBody

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = ServiceCreate

// AttachServiceToVPCJSONRequestBody defines body for AttachServiceToVPC for application/json ContentType.
type AttachServiceToVPCJSONRequestBody = ServiceVPCInput

// DetachServiceFromVPCJSONRequestBody defines body for DetachServiceFromVPC for application/json ContentType.
type DetachServiceFromVPCJSONRequestBody = ServiceVPCInput

// ForkServiceJSONRequestBody defines body for ForkService for application/json ContentType.
type ForkServiceJSONRequestBody = ForkServiceCreate

// GetServiceMetricsSeriesJSONRequestBody defines body for GetServiceMetricsSeries for application/json ContentType.
type GetServiceMetricsSeriesJSONRequestBody = MetricsSeriesRequest

// RenameServiceJSONRequestBody defines body for RenameService for application/json ContentType.
type RenameServiceJSONRequestBody = ServiceRename

// CreateReplicaSetJSONRequestBody defines body for CreateReplicaSet for application/json ContentType.
type CreateReplicaSetJSONRequestBody = ReadReplicaSetCreate

// ResizeReplicaSetJSONRequestBody defines body for ResizeReplicaSet for application/json ContentType.
type ResizeReplicaSetJSONRequestBody = ResizeInput

// SetReplicaEnvironmentJSONRequestBody defines body for SetReplicaEnvironment for application/json ContentType.
type SetReplicaEnvironmentJSONRequestBody = SetEnvironmentInput

// ResizeServiceJSONRequestBody defines body for ResizeService for application/json ContentType.
type ResizeServiceJSONRequestBody = ResizeInput

// SetEnvironmentJSONRequestBody defines body for SetEnvironment for application/json ContentType.
type SetEnvironmentJSONRequestBody = SetEnvironmentInput

// SetHAReplicaJSONRequestBody defines body for SetHAReplica for application/json ContentType.
type SetHAReplicaJSONRequestBody = SetHAReplicaInput

// UpdatePasswordJSONRequestBody defines body for UpdatePassword for application/json ContentType.
type UpdatePasswordJSONRequestBody = UpdatePasswordInput

// CreateVPCJSONRequestBody defines body for CreateVPC for application/json ContentType.
type CreateVPCJSONRequestBody = VPCCreate

// CreateVPCPeeringJSONRequestBody defines body for CreateVPCPeering for application/json ContentType.
type CreateVPCPeeringJSONRequestBody = PeeringCreate

// RenameVPCJSONRequestBody defines body for RenameVPC for application/json ContentType.
type RenameVPCJSONRequestBody = VPCRename
