package cmd

import (
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/timescale/tiger-cli/internal/config"
)

func TestServiceCreate_ValidationErrors(t *testing.T) {
	tmpDir := setupServiceTest(t)

	// Set up config with a mock API URL to prevent network calls
	_, err := config.UseTestConfig(tmpDir, map[string]any{
		"api_url": "http://localhost:9999", // Use a local URL that will fail fast
	})
	if err != nil {
		t.Fatalf("Failed to save test config: %v", err)
	}

	// Mock authentication
	mockTestPAT(t)

	// Test with no name (should auto-generate) - this should now work without error
	// Just test that it doesn't fail due to missing name
	_, _, err = executeServiceCommand(t.Context(), "service", "create", "--addons", "none", "--region", "us-east-1")
	// This should fail due to network/API call, not due to missing name
	if err != nil && (strings.Contains(err.Error(), "name") && strings.Contains(err.Error(), "required")) {
		t.Errorf("Should not fail due to missing name anymore (should auto-generate), got: %v", err)
	}

	// Test invalid addon - this should fail validation before making API call
	_, _, err = executeServiceCommand(t.Context(), "service", "create", "--addons", "invalid-addon", "--region", "us-east-1", "--cpu", "1000", "--memory", "4", "--replicas", "1")
	if err == nil {
		t.Fatal("Expected error when addon is invalid")
	}
	if !strings.Contains(err.Error(), "invalid add-on") {
		t.Errorf("Expected error about invalid add-on, got: %v", err)
	}
}

func TestServiceCreate_NoAuth(t *testing.T) {
	tmpDir := setupServiceTest(t)

	// Set up config with API URL
	_, err := config.UseTestConfig(tmpDir, map[string]any{
		"api_url": "https://api.tigerdata.com/public/v1",
	})
	if err != nil {
		t.Fatalf("Failed to save test config: %v", err)
	}

	// Mock authentication failure
	mockNotLoggedIn(t)

	// Execute service create command with valid parameters (name will be auto-generated)
	_, _, err = executeServiceCommand(t.Context(), "service", "create", "--addons", "none", "--region", "us-east-1", "--cpu", "1000", "--memory", "4", "--replicas", "1")
	if err == nil {
		t.Fatal("Expected error when not authenticated")
	}

	if !strings.Contains(err.Error(), "authentication required") {
		t.Errorf("Expected authentication error, got: %v", err)
	}
}

func TestAutoGeneratedServiceName(t *testing.T) {
	tmpDir := setupServiceTest(t)

	// Set up config with a mock API URL to prevent network calls
	_, err := config.UseTestConfig(tmpDir, map[string]any{
		"api_url": "http://localhost:9999", // Use a local URL that will fail fast
	})
	if err != nil {
		t.Fatalf("Failed to save test config: %v", err)
	}

	// Mock authentication
	mockTestPAT(t)

	// Test that service name is auto-generated when not provided
	// We expect this to fail at the API call stage, not at validation
	var rootCmd *cobra.Command
	_, rootCmd, err = executeServiceCommand(t.Context(), "service", "create", "--addons", "none", "--region", "us-east-1")

	// The command should not fail due to missing service name
	if err != nil && strings.Contains(err.Error(), "service name is required") {
		t.Error("Service name should be auto-generated, not required")
	}

	// Navigate to the create command that was actually used
	if rootCmd == nil {
		t.Fatal("rootCmd should not be nil")
	}

	// Find service command
	serviceCmd, _, err := rootCmd.Find([]string{"service"})
	if err != nil {
		t.Fatalf("Failed to find service command: %v", err)
	}

	// Find create subcommand
	createCmd, _, err := serviceCmd.Find([]string{"create"})
	if err != nil {
		t.Fatalf("Failed to find create command: %v", err)
	}

	nameFlag := createCmd.Flags().Lookup("name")
	if nameFlag == nil {
		t.Fatal("name flag should exist on create command")
	}

	serviceName := nameFlag.Value.String()
	if serviceName == "" {
		t.Error("Service name should have been auto-generated")
	}

	// Check pattern (should start with "db-" followed by numbers)
	if !strings.HasPrefix(serviceName, "db-") {
		t.Errorf("Auto-generated name should start with 'db-', got: %s", serviceName)
	}
}

func TestServiceCreate_WaitTimeoutParsing(t *testing.T) {
	tmpDir := setupServiceTest(t)

	// Set up config to get past initial validation
	_, err := config.UseTestConfig(tmpDir, map[string]any{
		"api_url": "http://localhost:9999", // Use local URL that will fail fast
	})
	if err != nil {
		t.Fatalf("Failed to save test config: %v", err)
	}

	// Mock authentication
	mockTestPAT(t)

	testCases := []struct {
		name          string
		waitTimeout   string
		expectError   bool
		errorContains string
	}{
		{
			name:        "Valid duration - minutes",
			waitTimeout: "30m",
			expectError: false,
		},
		{
			name:        "Valid duration - hours and minutes",
			waitTimeout: "1h30m",
			expectError: false,
		},
		{
			name:        "Valid duration - seconds",
			waitTimeout: "90s",
			expectError: false,
		},
		{
			name:        "Valid duration - hours",
			waitTimeout: "2h",
			expectError: false,
		},
		{
			name:          "Invalid duration format",
			waitTimeout:   "invalid",
			expectError:   true,
			errorContains: "invalid duration", // Cobra's parsing error
		},
		{
			name:          "Negative duration",
			waitTimeout:   "-30m",
			expectError:   true,
			errorContains: "wait timeout must be positive",
		},
		{
			name:          "Zero duration",
			waitTimeout:   "0s",
			expectError:   true,
			errorContains: "wait timeout must be positive",
		},
		{
			name:          "Empty duration",
			waitTimeout:   "",
			expectError:   true,
			errorContains: "invalid duration", // Cobra's parsing error
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Execute service create with specific wait-timeout
			_, _, err := executeServiceCommand(t.Context(), "service", "create",
				"--name", "test-service",
				"--addons", "none",
				"--region", "us-east-1",
				"--wait-timeout", tc.waitTimeout,
				"--no-wait") // Use no-wait to avoid actual API calls

			if tc.expectError {
				if err == nil {
					t.Errorf("Expected error for wait-timeout '%s', but got none", tc.waitTimeout)
					return
				}
				if !strings.Contains(err.Error(), tc.errorContains) {
					t.Errorf("Expected error to contain '%s', got: %v", tc.errorContains, err)
				}
			} else {
				// For valid durations, we expect authentication error since we're using mock API
				// The duration parsing should succeed and we should get to the API call stage
				if err != nil && strings.Contains(err.Error(), "invalid duration") {
					t.Errorf("Unexpected duration parsing error for '%s': %v", tc.waitTimeout, err)
				}
			}
		})
	}
}

func TestServiceCreate_NoSetDefaultFlag(t *testing.T) {
	// Test that the --no-set-default flag is recognized and doesn't cause parsing errors
	output, _, err := executeServiceCommand(t.Context(), "service", "create", "--help")
	if err != nil {
		t.Fatalf("Help command should not fail: %v", err)
	}

	// Verify the flag appears in help output
	if !strings.Contains(output, "--no-set-default") {
		t.Error("Expected --no-set-default flag to appear in help output")
	}

	// Verify the flag description
	if !strings.Contains(output, "Don't set this service as the default service") {
		t.Error("Expected --no-set-default flag description to appear in help output")
	}

	// Verify the help text mentions the default behavior
	if !strings.Contains(output, "newly created service will be set as your default service") {
		t.Error("Expected help text to mention default service behavior")
	}
}

func TestServiceCreate_OutputFlagDoesNotPersist(t *testing.T) {
	tmpDir := setupServiceTest(t)

	// Set up config with default output format (table)
	cfg, err := config.UseTestConfig(tmpDir, map[string]any{
		"api_url": "http://localhost:9999",
		"output":  "table", // Explicitly set default
	})
	if err != nil {
		t.Fatalf("Failed to setup test config: %v", err)
	}
	configFile := cfg.GetConfigFile()

	// Validate starting config file
	configMap := parseConfigFile(t, configFile)
	if outputVal, exists := configMap["output"]; !exists || outputVal != "table" {
		t.Fatalf("Expected initial output in config file to be 'table', got: %v", outputVal)
	}

	// Mock authentication
	mockTestPAT(t)

	// Execute service create with -o json flag
	// This will fail due to network error (localhost:9999 doesn't exist), but that's OK
	// We just want to verify that the config file doesn't get the output flag written to it
	_, _, _ = executeServiceCommand(t.Context(), "service", "create", "-o", "json", "--cpu", "shared", "--memory", "shared")

	configMap = parseConfigFile(t, configFile)
	if outputVal, exists := configMap["output"]; !exists || outputVal != "table" {
		t.Fatalf("Expected output in config file to be 'table', got: %v", outputVal)
	}
}
